# Generated by Django 4.1 on 2022-08-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_certificate',
            name='certificate',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
