# Generated by Django 4.1 on 2022-08-18 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cantact',
            name='motivation_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='home_page_model',
            name='about_us',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resume_certificate',
            name='certificate_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='edu_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
